services:

  petholidays-frontend:
    container_name: petholidays-frontend
    build:
      context: ./src/frontend
      dockerfile: Dockerfile 
    ports:
      - "80:80"  

  petholidays-core-webapi:
    container_name: petholidays-core-webapi
    build:
      context: ./src/backend/LosTomates.PetHolidays.Core
      dockerfile: LosTomates.PetHolidays.Core.WebApi/Dockerfile 
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - ConnectionStrings__CoreDb=Host=postgres;Port=5432;Database=PetHolidaysCore;User id=postgres;Password=password
    depends_on:
      - postgres
    networks:
      - pet-holidays-network 

  petholidays-auth-webapi:
    container_name: petholidays-auth-webapi
    build:
      context: ./src/backend/LosTomates.PetHolidays.Auth
      dockerfile: LosTomates.PetHolidays.Auth.WebApi/Dockerfile 
    ports:
      - "5002:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - ConnectionStrings__AuthDb=Host=postgres;Port=5434;Database=PetHolidaysAuth;User id=postgres;Password=password
    depends_on:
      - postgres
    networks:
      - pet-holidays-network 

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: PetHolidaysCore
    ports:
      - "5433:5432"
    volumes:
      - pet-holidays-core-volume:/var/lib/postgresql/data
    networks:
      - pet-holidays-network

  postgres-auth:
    image: postgres:latest
    container_name: postgres-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: PetHolidaysAuth
    ports:
      - "5434:5434"
    command: ["postgres", "-c", "port=5434"] 
    volumes:
      - pet-holidays-auth-volume:/var/lib/postgresql/data
    networks:
      - pet-holidays-network

networks:
  pet-holidays-network:
    driver: bridge

volumes:
  pet-holidays-core-volume:
  pet-holidays-auth-volume:
