services:

  petholidays-frontend:
    container_name: petholidays-frontend
    build:
      context: ./src/frontend
      dockerfile: Dockerfile 
    ports:
      - "80:80"  

  petholidays-core-webapi:
    container_name: petholidays-core-webapi
    build:
      context: ./src/backend/LosTomates.PetHolidays.Core
      dockerfile: LosTomates.PetHolidays.Core.WebApi/Dockerfile 
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CoreDb=Host=postgres;Port=5432;Database=PetHolidaysCore;User id=postgres;Password=password
    depends_on:
      - postgres
    networks:
      - pet-holidays-network 

  petholidays-auth-webapi:
    container_name: petholidays-auth-webapi
    build:
      context: ./src/backend/LosTomates.PetHolidays.Auth
      dockerfile: LosTomates.PetHolidays.Auth.WebApi/Dockerfile 
    ports:
      - "5002:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CoreDb=Host=postgres;Port=5432;Database=PetHolidaysCore;User id=postgres;Password=password
    depends_on:
      - postgres
    networks:
      - pet-holidays-network 

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: PetHolidaysCore
    ports:
      - "5433:5432"
    volumes:
      - pet-holidays-core-volume:/var/lib/postgresql/data
    networks:
      - pet-holidays-network

networks:
  pet-holidays-network:
    driver: bridge

volumes:
  pet-holidays-core-volume:
