name: core-service-ci
on:
    push:
      branches: [ "main", "develop" ]
      paths:
          - "src/backend/**"
    pull_request:
      branches: [ "main", "develop" ]
      paths:
          - "src/backend/**"
    workflow_dispatch:

jobs:
   build_job:
      runs-on: ubuntu-latest
      
      steps:
         - name: Get code
           uses: actions/checkout@v4
         
         - name: Setup .NET
           uses: actions/setup-dotnet@v4
           with:
              dotnet-version: ${{ env.DOTNET_VERSION }}
         
         - name: List files in repository 
           run: ls -alh
         
         - name: Install dependencies
           run: dotnet restore ./src/backend/LosTomates.PetHolidays.sln
           working-directory: ./src/backend
         
         - name: Build
           run: dotnet build ./src/backend/LosTomates.PetHolidays.sln --configuration Release --no-restore
           working-directory: . 
           
         - name: Test
           run: dotnet test ./src/backend/LosTomates.PetHolidays.sln --configuration Release --no-build
           working-directory: ./src/backend 
           
         - name: Run The end
           run: echo The end!
