<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>LosTomates.PetHolidays.Core.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.3.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.3.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LosTomates.PetHolidays.Core.Core\LosTomates.PetHolidays.Core.Core.csproj" />
    <ProjectReference Include="..\LosTomates.PetHolidays.Core.DataAccess\LosTomates.PetHolidays.Core.DataAccess.csproj" />
  </ItemGroup>

</Project>
